### ISSUE TITLE
パスタ麺の種類と歴史を調べる

### ISSUE THREAD

**Issue by rit-iniad** [Chicken-iniad/team-tuitui-project#11]
6つぐらい紹介しましょう

**Comment by Miumaru-iniad** [comment]
<a href="https://www.amazon.co.jp/Barilla-%E3%82%B9%E3%83%91%E3%82%B2%E3%83%83%E3%83%86%E3%82%A3No-5-1-7mm-5kg-%E6%AD%A3%E8%A6%8F%E8%BC%B8%E5%85%A5%E5%93%81/dp/B00HS9EEI0?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=1EWQBWUMP74VB&keywords=%E3%82%B9%E3%83%91%E3%82%B2%E3%83%83%E3%83%86%E3%82%A3&qid=1657076987&sprefix=%E3%82%B9%E3%83%91%E3%82%B2%E3%83%83%E3%83%86%E3%82%A3%2Caps%2C197&sr=8-5&linkCode=li3&tag=naritaicookin-22&linkId=1f36914f3c66fd7b6289a4792e8d0a9c&language=ja_JP&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B00HS9EEI0&Format=_SL250_&ID=AsinImage&MarketPlace=JP&ServiceVersion=20070822&WS=1&tag=naritaicookin-22&language=ja_JP" ></a><img src="https://ir-jp.amazon-adsystem.com/e/ir?t=naritaicookin-22&language=ja_JP&l=li3&o=9&a=B00HS9EEI0" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />

**Comment by Miumaru-iniad** [comment]
<a href="https://www.amazon.co.jp/Barilla-%E3%82%B9%E3%83%91%E3%82%B2%E3%83%83%E3%83%86%E3%82%A3No-5-1-7mm-5kg-%E6%AD%A3%E8%A6%8F%E8%BC%B8%E5%85%A5%E5%93%81/dp/B00HS9EEI0?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=1EWQBWUMP74VB&keywords=%E3%82%B9%E3%83%91%E3%82%B2%E3%83%83%E3%83%86%E3%82%A3&qid=1657076987&sprefix=%E3%82%B9%E3%83%91%E3%82%B2%E3%83%83%E3%83%86%E3%82%A3%2Caps%2C197&sr=8-5&linkCode=li3&tag=naritaicookin-22&linkId=1f36914f3c66fd7b6289a4792e8d0a9c&language=ja_JP&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B00HS9EEI0&Format=_SL250_&ID=AsinImage&MarketPlace=JP&ServiceVersion=20070822&WS=1&tag=naritaicookin-22&language=ja_JP" ></a><img src="https://ir-jp.amazon-adsystem.com/e/ir?t=naritaicookin-22&language=ja_JP&l=li3&o=9&a=B00HS9EEI0" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
アフィリエイトリンクです

**Comment by Miumaru-iniad** [comment]
完了しました
