### ISSUE TITLE
リンクを埋め込むための画像制作

### ISSUE THREAD

**Issue by Chicken-iniad** [Chicken-iniad/team-tuitui-project#14]
・各種SNSリンク
　　縦長の画像をお願いします。
・サイトロゴ(横長)
・パスタ診断
・パスタ診断YES/NO
・レシピ一覧

**Comment by rit-iniad** [comment]
了解致しました!!

**Comment by rit-iniad** [comment]
![image](https://user-images.githubusercontent.com/105835221/175494046-c433b8a3-7139-486e-a219-f4c3a3a601f6.jpeg)

**Comment by rit-iniad** [comment]
![image](https://user-images.githubusercontent.com/105835221/175496082-3386763a-5bf4-4f08-9e5f-dd9da31ab861.png)

**Comment by rit-iniad** [comment]
![image](https://user-images.githubusercontent.com/105835221/175496971-44ed675a-56b0-49b2-a3f0-c87f195f80d4.png)

**Comment by rit-iniad** [comment]
各種SNSリンクへの画像を作成しました！![image](https://user-images.githubusercontent.com/105835221/175507483-cac9683f-79e9-437c-8eae-58380b89f0be.png)

**Comment by Chicken-iniad** [comment]
ありがとうございます！トップページに張り付けておきます。

**Comment by rit-iniad** [comment]
パスタ一覧の余白にこの画像を入れます！
![image](https://user-images.githubusercontent.com/105835221/176212988-261f5514-6a3e-4870-a989-80f6a2ff17d0.png)

**Comment by rit-iniad** [comment]
![image](https://user-images.githubusercontent.com/105835221/176217725-11862fbc-a9a6-4ff4-bb8c-0a62beb4b9ae.png)
