### ISSUE TITLE
ワイヤーフレームを作る

### ISSUE THREAD

**Issue by Miumaru-iniad** [Chicken-iniad/team-tuitui-project#4]
サイトのワイヤーフレームをGoogle Slidesで作る

**Comment by Chicken-iniad** [comment]
こちらです
https://docs.google.com/presentation/d/1Y0i2K8Ac49GWYBxWNTk5TR487rhq_zmhZpHy1Y8dywo/edit?usp=sharing

**Comment by Chicken-iniad** [comment]
ワイヤーフレームの作成終了しました！画面遷移図の作成に取り掛かります
