### ISSUE TITLE
画面遷移図の作成

### ISSUE THREAD

**Issue by Miumaru-iniad** [Chicken-iniad/team-tuitui-project#5]
画面遷移図を作成する

**Comment by Chicken-iniad** [comment]
![パスタ画面遷移図](https://user-images.githubusercontent.com/104750455/174434368-b0634fc8-86ed-4376-95ca-9177a85aa624.png)
仮で作りました。皆さん確認とレスポンスお願いします。

**Comment by Miumaru-iniad** [comment]
確認しました。レシピ診断とレシピ一覧は、レシピ診断の方が強いコンテンツになると思うので左右を入れ替えた方がいいかもしれないと思いました。

**Comment by Chicken-iniad** [comment]
わかりました、変更します。

**Comment by Chicken-iniad** [comment]
![Whiteboard](https://user-images.githubusercontent.com/104750455/174534503-2521b6a3-7c91-48df-ab23-ca34f2160809.png
ご指摘いただいたところを修正しました。再度確認をよろしくお願いします。

**Comment by Miumaru-iniad** [comment]
確認完了しました。この遷移図で行きましょう！クローズしてもらって大丈夫だと思います！

**Comment by rit-iniad** [comment]
ありがとうございます。
