### ISSUE TITLE
amazonアソシエイトのアカウント作成・利用方法の確認

### ISSUE THREAD

**Issue by Chicken-iniad** [Chicken-iniad/team-tuitui-project#6]
サイト閲覧者のamazon購入のおこぼれにあずかるためにアカウント作成と詳しい使い方の確認をします。

**Comment by Chicken-iniad** [comment]
https://www.xserver.ne.jp/blog/about-amazon-affiliate/
20歳～じゃないと登録ができず、審査が必要とのこと………
審査自体は通り方のコツなどがあるようなのでそこまで難しくはなさそう、収益化はJSの実装後余裕があったらにしましょう

**Comment by rit-iniad** [comment]
はい！

**Comment by Miumaru-iniad** [comment]
22ちゃい！

**Comment by Miumaru-iniad** [comment]
完了
