### ISSUE TITLE
紹介するパスタレシピの決定

### ISSUE THREAD

**Issue by Chicken-iniad** [Chicken-iniad/team-tuitui-project#8]
ページの作成と同時進行でレシピの文章化も進めたいため、紹介する8つのレシピを決めましょう。
今週中に決めておかないとみうまるの無限パスタが確定してしまうので今週中には話し合って決めよう

**Comment by rit-iniad** [comment]
いくつか考えております！

**Comment by Miumaru-iniad** [comment]
冷製パスタ２
ミートソース２
魚介パスタ２
ジェノベーゼ１
和風パスタ１
でどうかなと思っております！

**Comment by Chicken-iniad** [comment]
いいですね………！それでいきますか

**Comment by rit-iniad** [comment]
おいしそう✨
